type RarityTier = "common" | "uncommon" | "rare" | "ultra_rare";

interface PokemonEntry {
  id: number;
  name: string;
  rarityTier: RarityTier;
}

export const POKEMON_DATA: PokemonEntry[] = [
  // --- Common (~58) ---
  { id: 10, name: "Caterpie", rarityTier: "common" },
  { id: 11, name: "Metapod", rarityTier: "common" },
  { id: 13, name: "Weedle", rarityTier: "common" },
  { id: 14, name: "Kakuna", rarityTier: "common" },
  { id: 16, name: "Pidgey", rarityTier: "common" },
  { id: 17, name: "Pidgeotto", rarityTier: "common" },
  { id: 19, name: "Rattata", rarityTier: "common" },
  { id: 20, name: "Raticate", rarityTier: "common" },
  { id: 21, name: "Spearow", rarityTier: "common" },
  { id: 22, name: "Fearow", rarityTier: "common" },
  { id: 23, name: "Ekans", rarityTier: "common" },
  { id: 24, name: "Arbok", rarityTier: "common" },
  { id: 27, name: "Sandshrew", rarityTier: "common" },
  { id: 28, name: "Sandslash", rarityTier: "common" },
  { id: 29, name: "Nidoran F", rarityTier: "common" },
  { id: 32, name: "Nidoran M", rarityTier: "common" },
  { id: 35, name: "Clefairy", rarityTier: "common" },
  { id: 39, name: "Jigglypuff", rarityTier: "common" },
  { id: 41, name: "Zubat", rarityTier: "common" },
  { id: 42, name: "Golbat", rarityTier: "common" },
  { id: 43, name: "Oddish", rarityTier: "common" },
  { id: 44, name: "Gloom", rarityTier: "common" },
  { id: 46, name: "Paras", rarityTier: "common" },
  { id: 47, name: "Parasect", rarityTier: "common" },
  { id: 48, name: "Venonat", rarityTier: "common" },
  { id: 49, name: "Venomoth", rarityTier: "common" },
  { id: 50, name: "Diglett", rarityTier: "common" },
  { id: 51, name: "Dugtrio", rarityTier: "common" },
  { id: 52, name: "Meowth", rarityTier: "common" },
  { id: 54, name: "Psyduck", rarityTier: "common" },
  { id: 56, name: "Mankey", rarityTier: "common" },
  { id: 60, name: "Poliwag", rarityTier: "common" },
  { id: 63, name: "Abra", rarityTier: "common" },
  { id: 66, name: "Machop", rarityTier: "common" },
  { id: 69, name: "Bellsprout", rarityTier: "common" },
  { id: 72, name: "Tentacool", rarityTier: "common" },
  { id: 74, name: "Geodude", rarityTier: "common" },
  { id: 75, name: "Graveler", rarityTier: "common" },
  { id: 77, name: "Ponyta", rarityTier: "common" },
  { id: 79, name: "Slowpoke", rarityTier: "common" },
  { id: 81, name: "Magnemite", rarityTier: "common" },
  { id: 84, name: "Doduo", rarityTier: "common" },
  { id: 86, name: "Seel", rarityTier: "common" },
  { id: 88, name: "Grimer", rarityTier: "common" },
  { id: 90, name: "Shellder", rarityTier: "common" },
  { id: 92, name: "Gastly", rarityTier: "common" },
  { id: 96, name: "Drowzee", rarityTier: "common" },
  { id: 98, name: "Krabby", rarityTier: "common" },
  { id: 100, name: "Voltorb", rarityTier: "common" },
  { id: 102, name: "Exeggcute", rarityTier: "common" },
  { id: 104, name: "Cubone", rarityTier: "common" },
  { id: 109, name: "Koffing", rarityTier: "common" },
  { id: 116, name: "Horsea", rarityTier: "common" },
  { id: 118, name: "Goldeen", rarityTier: "common" },
  { id: 120, name: "Staryu", rarityTier: "common" },
  { id: 129, name: "Magikarp", rarityTier: "common" },
  { id: 133, name: "Eevee", rarityTier: "common" },
  { id: 147, name: "Dratini", rarityTier: "common" },

  // --- Uncommon (~58) ---
  { id: 1, name: "Bulbasaur", rarityTier: "uncommon" },
  { id: 4, name: "Charmander", rarityTier: "uncommon" },
  { id: 7, name: "Squirtle", rarityTier: "uncommon" },
  { id: 12, name: "Butterfree", rarityTier: "uncommon" },
  { id: 15, name: "Beedrill", rarityTier: "uncommon" },
  { id: 18, name: "Pidgeot", rarityTier: "uncommon" },
  { id: 25, name: "Pikachu", rarityTier: "uncommon" },
  { id: 26, name: "Raichu", rarityTier: "uncommon" },
  { id: 30, name: "Nidorina", rarityTier: "uncommon" },
  { id: 33, name: "Nidorino", rarityTier: "uncommon" },
  { id: 36, name: "Clefable", rarityTier: "uncommon" },
  { id: 37, name: "Vulpix", rarityTier: "uncommon" },
  { id: 38, name: "Ninetales", rarityTier: "uncommon" },
  { id: 40, name: "Wigglytuff", rarityTier: "uncommon" },
  { id: 45, name: "Vileplume", rarityTier: "uncommon" },
  { id: 53, name: "Persian", rarityTier: "uncommon" },
  { id: 55, name: "Golduck", rarityTier: "uncommon" },
  { id: 57, name: "Primeape", rarityTier: "uncommon" },
  { id: 58, name: "Growlithe", rarityTier: "uncommon" },
  { id: 59, name: "Arcanine", rarityTier: "uncommon" },
  { id: 61, name: "Poliwhirl", rarityTier: "uncommon" },
  { id: 64, name: "Kadabra", rarityTier: "uncommon" },
  { id: 67, name: "Machoke", rarityTier: "uncommon" },
  { id: 70, name: "Weepinbell", rarityTier: "uncommon" },
  { id: 73, name: "Tentacruel", rarityTier: "uncommon" },
  { id: 78, name: "Rapidash", rarityTier: "uncommon" },
  { id: 80, name: "Slowbro", rarityTier: "uncommon" },
  { id: 82, name: "Magneton", rarityTier: "uncommon" },
  { id: 83, name: "Farfetchd", rarityTier: "uncommon" },
  { id: 85, name: "Dodrio", rarityTier: "uncommon" },
  { id: 87, name: "Dewgong", rarityTier: "uncommon" },
  { id: 89, name: "Muk", rarityTier: "uncommon" },
  { id: 91, name: "Cloyster", rarityTier: "uncommon" },
  { id: 93, name: "Haunter", rarityTier: "uncommon" },
  { id: 95, name: "Onix", rarityTier: "uncommon" },
  { id: 97, name: "Hypno", rarityTier: "uncommon" },
  { id: 99, name: "Kingler", rarityTier: "uncommon" },
  { id: 101, name: "Electrode", rarityTier: "uncommon" },
  { id: 105, name: "Marowak", rarityTier: "uncommon" },
  { id: 106, name: "Hitmonlee", rarityTier: "uncommon" },
  { id: 107, name: "Hitmonchan", rarityTier: "uncommon" },
  { id: 108, name: "Lickitung", rarityTier: "uncommon" },
  { id: 110, name: "Weezing", rarityTier: "uncommon" },
  { id: 111, name: "Rhyhorn", rarityTier: "uncommon" },
  { id: 117, name: "Seadra", rarityTier: "uncommon" },
  { id: 119, name: "Seaking", rarityTier: "uncommon" },
  { id: 121, name: "Starmie", rarityTier: "uncommon" },
  { id: 122, name: "Mr. Mime", rarityTier: "uncommon" },
  { id: 124, name: "Jynx", rarityTier: "uncommon" },
  { id: 125, name: "Electabuzz", rarityTier: "uncommon" },
  { id: 126, name: "Magmar", rarityTier: "uncommon" },
  { id: 127, name: "Pinsir", rarityTier: "uncommon" },
  { id: 128, name: "Tauros", rarityTier: "uncommon" },
  { id: 132, name: "Ditto", rarityTier: "uncommon" },
  { id: 137, name: "Porygon", rarityTier: "uncommon" },
  { id: 138, name: "Omanyte", rarityTier: "uncommon" },
  { id: 140, name: "Kabuto", rarityTier: "uncommon" },
  { id: 148, name: "Dragonair", rarityTier: "uncommon" },

  // --- Rare (~25) ---
  { id: 2, name: "Ivysaur", rarityTier: "rare" },
  { id: 5, name: "Charmeleon", rarityTier: "rare" },
  { id: 8, name: "Wartortle", rarityTier: "rare" },
  { id: 31, name: "Nidoqueen", rarityTier: "rare" },
  { id: 34, name: "Nidoking", rarityTier: "rare" },
  { id: 62, name: "Poliwrath", rarityTier: "rare" },
  { id: 65, name: "Alakazam", rarityTier: "rare" },
  { id: 68, name: "Machamp", rarityTier: "rare" },
  { id: 71, name: "Victreebel", rarityTier: "rare" },
  { id: 76, name: "Golem", rarityTier: "rare" },
  { id: 103, name: "Exeggutor", rarityTier: "rare" },
  { id: 112, name: "Rhydon", rarityTier: "rare" },
  { id: 113, name: "Chansey", rarityTier: "rare" },
  { id: 114, name: "Tangela", rarityTier: "rare" },
  { id: 115, name: "Kangaskhan", rarityTier: "rare" },
  { id: 123, name: "Scyther", rarityTier: "rare" },
  { id: 130, name: "Gyarados", rarityTier: "rare" },
  { id: 131, name: "Lapras", rarityTier: "rare" },
  { id: 134, name: "Vaporeon", rarityTier: "rare" },
  { id: 135, name: "Jolteon", rarityTier: "rare" },
  { id: 136, name: "Flareon", rarityTier: "rare" },
  { id: 139, name: "Omastar", rarityTier: "rare" },
  { id: 141, name: "Kabutops", rarityTier: "rare" },
  { id: 142, name: "Aerodactyl", rarityTier: "rare" },
  { id: 143, name: "Snorlax", rarityTier: "rare" },

  // --- Ultra Rare (10) ---
  { id: 3, name: "Venusaur", rarityTier: "ultra_rare" },
  { id: 6, name: "Charizard", rarityTier: "ultra_rare" },
  { id: 9, name: "Blastoise", rarityTier: "ultra_rare" },
  { id: 94, name: "Gengar", rarityTier: "ultra_rare" },
  { id: 144, name: "Articuno", rarityTier: "ultra_rare" },
  { id: 145, name: "Zapdos", rarityTier: "ultra_rare" },
  { id: 146, name: "Moltres", rarityTier: "ultra_rare" },
  { id: 149, name: "Dragonite", rarityTier: "ultra_rare" },
  { id: 150, name: "Mewtwo", rarityTier: "ultra_rare" },
  { id: 151, name: "Mew", rarityTier: "ultra_rare" },
];

export function getSpriteUrl(pokedexNumber: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokedexNumber}.png`;
}
